### ISSUE TITLE
Layout cache

### ISSUE THREAD

**Issue by xenopont** [xenopont/jsapp#2]
Page layouts must be cached and not rebuilt again on every page switch.

**Comment by xenopont** [comment]
cache is not important, localization has a higher priority

**Comment by slavawashere** [comment]
My name is Slava, i'm from Russia20:52, 25 декабря 2016 г., John Smith <notifications@github.com>:cache is not important, localization has a higher priority

**Comment by xenopont** [comment]
Karasho, @slavawashere Slava! Mi est pytazzo localizovayten der programma. Fershteenst Du?
